### ISSUE TITLE
OTEL in native tools

### ISSUE THREAD

**Issue by xmxnt** [masaic-ai-platform/open-responses#63]

**Comment by jas34** [comment]
@codefromthecrypt, thanks for the inputs.
Are you referring to the variables mentioned in [application-otel.properties](https://github.com/masaic-ai-platform/open-responses/blob/main/src/main/resources/application-otel.properties)?

**Comment by codefromthecrypt** [comment]
I would like to set a single endpoint env and use the exact protocol OTEL_EXPORTER_OTLP_PROTOCOL value for http+proto instead of having to set a spring profile and a second env for metrics.

I think if you make an autoconfiguration on your own you can overcome the limitations and not need these. I have made custom conditions in zipkin for the same reason (hide spring details and make it feel like a normal process)

**Comment by codefromthecrypt** [comment]
Another way is to do like my example app does and use the Java agent for otel config. Then you don't have to check each and every env to make sure they are really same as otel as all would be the same.

Up to you on how to do this but typically I set 3 env: service name, endpoint (for all things traces logs metrics) and otlp proto (usually to http with protob). So the ideal is not having to do something different here.

**Comment by codefromthecrypt** [comment]
here are example ENV that I can use in any otel SDK (java, python, node etc) due to sharing configuration.

So if you choose not to use otel directly which would give all of these, you can make custom auto-configuration and still work. 

```
# Set to false, if you want to record logs, traces and metrics.
OTEL_SDK_DISABLED=true

# Assign the service name that shows up in Kibana
OTEL_SERVICE_NAME=chatbot-rag-app

# Default to send logs, traces and metrics to an OpenTelemetry collector,
# accessible via localhost. For example, Elastic Distribution of OpenTelemetry
# (EDOT) Collector.
#
# When running inside Kubernetes, set to http://otel-collector.default.svc:4318
# or similar.
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

# Change to 'false' to hide prompt and completion content
OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true

# Export metrics every 3 seconds instead of every minute
OTEL_METRIC_EXPORT_INTERVAL=3000
# Export traces every 3 seconds instead of every 5 seconds
OTEL_BSP_SCHEDULE_DELAY=3000
```

When I led zipkin, the choice to use spring boot wasn't 100pct desired, esp for folks outside java. Some reasons included using different ENV which are native to spring but not to upstream.

To make it feel like "a normal process" required leaning into that. Your choices are your own, but just sharing how I dealt with this some time back. e.g. taking plain variables and deciding to use them or not based on conditions. loading profiles that use these variables by default https://github.com/openzipkin/zipkin/blob/b7e22588e8d978939f2c8c7da5bb13d1467facbd/zipkin-server/src/main/java/zipkin2/server/internal/rabbitmq/ZipkinRabbitMQCollectorConfiguration.java#L37-L49

my 2p and hope it helps!

**Comment by jas34** [comment]
Sounds good. We will implement accordingly!

**Comment by jas34** [comment]
The dependency on the spring profile has been removed. Release 0.2.0-M2 onwards OpenResponses is compliant to environment variables specified at https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/

@codefromthecrypt, The following configuration should be valid for OpenResponses also.
> here are example ENV that I can use in any otel SDK (java, python, node etc) due to sharing configuration.

**Comment by codefromthecrypt** [comment]
maybe you can double-check this as I'm not getting server-side traces (with or without the profile)

```yaml
services:
  open-responses:
    image: masaicai/open-responses:0.2.0-M2
    container_name: open-responses
    environment:
      - SPRING_PROFILES_ACTIVE=otel
      - OTEL_SERVICE_NAME=open-responses
      - MODEL_BASE_URL=http://host.docker.internal:11434/v1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
        - "8080:8080"
```
